### ISSUE TITLE
Convert the project code to use ES6 standards

### ISSUE THREAD

**Issue by Asuza** [JSJitsu/ai-battle-engine#11]
The battle engine was written a few years ago and could use some updating. Rather than using prototypes, update the engine to use classes instead. Remove `var` statements in favor of `let` or `const`, and use arrow functions (where it makes sense to) in place of standard functions.

**Comment by adityaparab** [comment]
Cool... Got here from hactoberfest github filter. I'd love to work on this.

**Comment by romainwn** [comment]
Hey, I will try to start working on this in the next few days :)

**Comment by Asuza** [comment]
It's all yours, @adityaparab.

**Comment by romainlq** [comment]
Looks like I missed the train ! Shouldn't you guys make the PR starting from October 1st ? I mean, if you're here for Hacktoberfest..

**Comment by Asuza** [comment]
@wildan3105, I appreciate your eagerness to get a PR ready to go, but I'm going to have to give @adityaparab a chance to submit a PR to be merged as well. If you do want to work on a different issue, please claim it via a comment so others don't unintentionally spend time on fixing something that may not end up getting merged.

You're probably right, @romainwn, though I can't blame anyone for wanting to get started as early as possible. I'll be creating more issues as soon as I have time in this and the other @JSJitsu repos, if you're interested. I always _try_ to explain each issue in detail and make the issues relatively straightforward and self-contained.

**Comment by wildan3105** [comment]
got that :ok:

**Comment by Asuza** [comment]
Closed via #17. Thanks, @adityaparab!
