### ISSUE TITLE
Allow maps to have spawn points

### ISSUE THREAD

**Issue by Asuza** [JSJitsu/ai-battle-engine#12]
Currently, players are placed in random locations on the map. Continue to allow this (see https://github.com/JSJitsu/ai-battle-engine/blob/672fd5bdeb1503bc4063aebda2e88eacec3cf87e/index.js#L166) but also allow maps to contain an indicator that a specific block is a spawn point.

For example, if a map looked like this:
```
S1|  |  |  |S2
S1|  |IM|  |S2
S1|  |IM|  |S2
S1|  |  |  |S2
```
The engine should put team 1 players into _S1_ tiles, and team 2 players into _S2_ tiles. _SP_ should place a player from any team in that tile.

If a map that gets loaded contains *any* spawn points, then the engine should *not* randomly place any players. There should also be a safety check that there are enough spawn points for all players, and if not, log an error and fall back to random placement.

**Comment by himanshujariyal** [comment]
@Asuza I'd like to work on this feature.

**Comment by Asuza** [comment]
Thanks, @himanshujariyal. Let me know if you have any questions.

**Comment by Asuza** [comment]
This is still a valid Hacktoberfest issue, as it was never completely finished. Feel free to either start from scratch or use the existing PR from @himanshujariyal.

**Comment by redice44** [comment]
I'll take a crack at it this year. 😄

**Comment by redice44** [comment]
@Asuza PR is up for this issue 😄  Please take a look and let me know what you think 👍

**Comment by Asuza** [comment]
Enhanced via #26. Thanks, @redice44!
