### ISSUE TITLE
Install eslint and copy rules from ai-battle-website

### ISSUE THREAD

**Issue by Asuza** [JSJitsu/ai-battle-engine#5]
We need consistent code!
- Install [eslint](https://www.npmjs.com/package/eslint) and save it as a package dependency.
- Add the rules from the [ai-battle-website](https://github.com/JSJitsu/ai-battle-website/) repository to this one.
- Ensure the linter can be run by adding a "lint" script to _package.json_.

Bonus: Use eslint to automatically fix existing linting issues.

**Comment by dmnkgrc** [comment]
Hi! Can I take a look at this? The link to the ai-battle-website takes me to a 404 page :/

**Comment by Asuza** [comment]
Definitely, @dmnkgrc. Sorry, I fixed the link.

**Comment by Asuza** [comment]
Fixed by #7.
