### ISSUE TITLE
Implement tests for handling the hero's move

### ISSUE THREAD

**Issue by Asuza** [JSJitsu/ai-battle-engine#8]
Create tests to replace these placeholders:

**Handle hero move**
- Should not let the hero move off of the board.
- Should move the hero in the right direction.
- Should leave the previous tile unoccupied.

You can run the tests with `npm test`. Of course, feel free to include any extra (or new) tests that make sense.

**Comment by gendelbendel** [comment]
Please see PR #9 for the requested test implementation, as well as the rest of the test cases fixed.

Fixing the rest of the tests was probably a separate issue entirely, but hey, I was already on the testing train.

If you'd like any more assistance, let me know! Seems like a fun project and I'm going for the Hacktoberfest participation.
